name: Practice - Deploy Project (Workflow 1A)
# deploy using only 1 job

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
